### ISSUE TITLE
[All] _devicekey' referenced before assignment

### ISSUE THREAD

**Issue by hmol33** [dut-iptv/dut-iptv.github.io#14]
als ik wil inloggen bij canal digitaal krijg ik een vreemd error dat er fouten staan in een script

**Comment by dut-iptv** [comment]
Please enable debug logging and provide a Kodi debug log after the error has occurred

**Comment by hmol33** [comment]
![Schermafdruk van 2020-09-28 22-41-49](https://user-images.githubusercontent.com/31893233/94484058-1e6fac00-01dc-11eb-85a5-6f22cd1cfd20.png)

**Comment by hmol33** [comment]
2020-09-28 22:45:16.304 T:140320801023744   ERROR: plugin.video.canaldigitaal - local variable '_devicekey' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/hans/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/home/hans/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 94, in dispatch
                                                function(**params)
                                              File "/home/hans/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 44, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/home/hans/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 72, in login
                                                log.debug('Devicekey: {devicekey}'.format(devicekey=_devicekey))
                                            UnboundLocalError: local variable '_devicekey' referenced before assignment
2020-09-28 22:45:18.536 T:140324111750016 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2020-09-28 22:45:18.669 T:140318955513600 WARNING: Previous line repeats 15 times.
2020-09-28 22:45:18.669 T:140318955513600   ERROR: GetDirectory - Error getting plugin://plugin.video.canaldigitaal/?_=login
2020-09-28 22:45:18.685 T:140324111750016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canaldigitaal/?_=login) failed

**Comment by dut-iptv** [comment]
Clear. Thanks for the report. Bug was introduced in a recent update. Will try to fix ASAP, but addons are undergoing a rewrite at this time and I don't have much spare time. So it clould be a week or 2 before I get around to fixing it.

**Comment by mcmurdy** [comment]
The KPN Plugin has the same error....

**Comment by dut-iptv** [comment]
KPN Addon should be fixed.
Canaldigitaal / NLZiet / Tmobile / Ziggo to follow

**Comment by dut-iptv** [comment]
Canaldigitaal errors should be fixed, but because I don't have access to an account right now, I can't really do any testing beyond saying that it does not crash when starting the addon.

**Comment by dut-iptv** [comment]
KPN, NLZiet, T-mobile and Canaldigitaal should be fixed.

KPN and T-Mobile have been tested and found to be working.
NLZiet still has some problems that are being worked on in #22
No word on Canal Digitaal yet and I don't have an option to test the addon myself.
A fix for Ziggo is in development

**Comment by dut-iptv** [comment]
NLZiet is fixed.

Ziggo is still being worked on, but this specific error does not occur on Ziggo.

Closing this issue for now
