### ISSUE TITLE
[NLZiet] Addon not working

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv.github.io#16]
Hello,

I am unable to watch Live TV and Replay TV.
Yesterday the All programs functions (VOD) worked fine but now also doesn't play anything.

Live Tv

https://paste.kodi.tv/povekowaxi.kodi

Replay Tv

https://paste.kodi.tv/vuyafixuli.kodi

All programs

Update: Seems to be working every now and then/randomly
Update 2: Found the fix. You need to sign out of all sessions using
https://www.nlziet.nl/DeviceLogoff

This makes me think the addon keeps the sessions alive whenever you are done watching something.
And perhaps there's a limit of X sessions for every X hours.

https://paste.kodi.tv/wicedugodi.kodi

Note: Sometimes when selecting a program under All programs it does show the episodes but gives an title error when trying to play.

https://paste.kodi.tv/enanifikiq.kodi

Setup:
Raspberry Pi 3B+
LibreELEC 9.2.4

**Comment by Nigel1992** [comment]
Live TV

```

2020-10-03 22:05:29.633 T:1790935936   ERROR: GetDirectory - Error getting plugin://plugin.video.nlziet/?_=replaytv
2020-10-03 22:05:29.667 T:1937381824   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nlziet/?_=replaytv) failed
2020-10-03 22:05:30.991 T:895906688   ERROR: plugin.video.nlziet - 'module' object has no attribute 'warning'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/base/router.py", line 94, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/base/plugin.py", line 44, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/plugin.py", line 111, in live_tv
                                                for row in get_live_channels(addon=settings.getBool(key='enable_simple_iptv')):
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/plugin.py", line 1098, in get_live_channels
                                                (_.START_BEGINNING, 'RunPlugin({context_url})'.format(context_url=plugin.url_for(func_or_url=play_video, type='channel', channel=channeldata['channel_id'], id=None, from_beginning=True)), ),
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/base/language.py", line 125, in __getattribute__
                                                return addon_string(attr)
                                              File "/storage/.kodi/addons/plugin.video.nlziet/resources/lib/base/language.py", line 32, in addon_string
                                                log.warning("LANGUAGE: Addon didn't return a string for id: {}".format(id))
                                            AttributeError: 'module' object has no attribute 'warning'

```

**Comment by Nigel1992** [comment]
Update: version .96

After resetting the addon it gives me an error nonce is not defined.

**Comment by dut-iptv** [comment]
Latest version should have different error and session handling which should fix these errors (might introduce others though)

Let's continue discussion in #22
