### ISSUE TITLE
Unable to sign in to Ziggo

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv.github.io#2]
After providing my username and password it tells me my login is incorrect.

My username is my email as that works on the normal ziggo and ziggo go site ![image](https://user-images.githubusercontent.com/5491930/86638331-63b68000-bfd7-11ea-8ffd-7c5fdafe1ac5.jpeg)

**Comment by dut-iptv** [comment]
I'm unaware of any problems with using an email for login, but I also don't have an account with an email instead of an username that is used for login to test this. If I look at the technical side of the login procedure on ziggogo.tv there does not seem to be any difference between using an email and using a regular username.

Are you absolutely sure your login information works on ziggogo.tv? 
Have you tried copy/pasting your information?
Have you tried temporarily changing your password to an easy combination of letters/numbers to rule out a problem related to your password?

**Comment by pepijng** [comment]
Same issue here, can't login and 100% sure the credentials are ok. Does not work on multiple devices.
`2020-07-07 10:19:37.247 T:113240   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ziggo/?_=login
2020-07-07 10:19:37.259 T:116448   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ziggo/?_=login) failed
2020-07-07 10:19:37.819 T:103964   ERROR: C:\Users\xxx\AppData\Roaming\Kodi\addons\script.module.fuzzywuzzy\lib\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                              warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')`

**Comment by Micro-Crackedto** [comment]
I am 100% sure my credentials are correct.

**Comment by dut-iptv** [comment]
I have enabled some additional logging in the latest version of the Ziggo addon (9.9.20).
Please enable debug logging in Kodi Settings, update to the latest version of the addon and then provide me a Kodi debug log after you have tried to log in. 
I'm looking for the part starting with "STATUS CODE" and ending with "URL".

**Comment by pepijng** [comment]
As requested, the logfile.

I noticed this error

```
2020-07-08 10:58:20.215 T:4300   DEBUG: plugin.video.ziggo - Attempt 1/2: POST https://web-api-pepper.horizon.tv/oesp/v2/NL/nld/web/session
2020-07-08 10:58:21.203 T:4032    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://dut-iptv.github.io (easy=0x23350304920, multi=0x2334b32a200)
2020-07-08 10:58:22.359 T:4300   DEBUG: plugin.video.ziggo - STATUS CODE: 403
2020-07-08 10:58:22.360 T:4300   DEBUG: plugin.video.ziggo - DATA
2020-07-08 10:58:22.360 T:4300   DEBUG: plugin.video.ziggo - {"system":"OESP","reason":"wrong backoffice"}

```
[Ziggo-Kodi-Log.txt](https://github.com/dut-iptv/dut-iptv.github.io/files/4889671/Ziggo-Kodi-Log.txt)

**Comment by dut-iptv** [comment]
Would you be able to do the following:
-Launch chrome/firefox on your computer
-Enable Developer console using Ctrl + Shift + I or F12
-Open the network tab
-Browse to https://www.ziggogo.tv/
-Clear the contents of the network tab using the clear button
-Login to Ziggo Go using your credentials
-Find mentions to "session" in the network tab, there will be multiple
-Right click the last "session" entry  (should be a POST request) and click "Copy" -> "Copy as Powershell"
-Past in a text editor and replace any mention to your email address and password
-Copy and paste the resulting output here

**Comment by pepijng** [comment]
as requested
```
Invoke-WebRequest -Uri "https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/session" `
-Method "POST" `
-Headers @{
"Accept"="application/json"
  "X-Client-Id"="1.4.25.14||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
  "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
  "Origin"="https://www.ziggogo.tv"
  "Sec-Fetch-Site"="cross-site"
  "Sec-Fetch-Mode"="cors"
  "Sec-Fetch-Dest"="empty"
  "Referer"="https://www.ziggogo.tv/obo_nl.html"
  "Accept-Encoding"="gzip, deflate, br"
  "Accept-Language"="en-US,en;q=0.9,nl;q=0.8"
} `
-ContentType "application/json" `
-Body "{`"username`":`"<myemail>`",`"password`":`"<mypassword>`"}"
```

**Comment by dut-iptv** [comment]
It seems some accounts need to connect to the endpoint at https://web-api-prod-obo.horizon.tv/oesp/v3 while some accounts need to connect to https://web-api-pepper.horizon.tv/oesp/v2.

I have created a function to automatically switch to the other endpoint if the addon receives the "wrong backoffice" message.

Please try version 0.9.9.21 of the addon to see if the problem is fixed.

**Comment by pepijng** [comment]
I've tried the latest release (manual it could not be updated from the repository) and attached the errormessage and logfile

![image](https://user-images.githubusercontent.com/6169050/86956104-dbf87f00-c158-11ea-806a-ce5ec0b95caf.png)
[kodi.log](https://github.com/dut-iptv/dut-iptv.github.io/files/4892537/kodi.log)

**Comment by pepijng** [comment]
After I executed 'Reset addon' the following error occured

```
2020-07-08 20:26:37.902 T:1416   DEBUG: plugin.video.ziggo - Attempt 1/2: POST
2020-07-08 20:26:37.916 T:1416   DEBUG: plugin.video.ziggo - Attempt 2/2: POST
2020-07-08 20:26:37.916 T:1416   DEBUG: plugin.video.ziggo - SIGNAL: on_exception
2020-07-08 20:26:37.919 T:1416   ERROR: plugin.video.ziggo - Invalid URL '': No schema supplied. Perhaps you meant http://?
                                            Traceback (most recent call last):
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\signals.py", line 29, in throwable
                                                yield
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\router.py", line 94, in dispatch
                                                function(**params)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\plugin.py", line 43, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\plugin.py", line 68, in login
                                                api.login(username=username, password=password, channels=True)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\api.py", line 69, in login
                                                data = self.download(url=settings.get(key='_session_url'), type="post", code=None, data={"username": username, "password": password}, json_data=True, data_return=True, return_json=True, retry=retry, check_data=False)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\api.py", line 353, in download
                                                resp = self._session.post(url, json=data)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 581, in post
                                                return self.request('POST', url, data=data, json=json, **kwargs)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\session.py", line 45, in request
                                                data = super(Session, self).request(method, url, **kwargs)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 387, in prepare_url
                                                raise MissingSchema(error)
                                            MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-08 20:26:37.919 T:1416   DEBUG: plugin.video.ziggo - SIGNAL: on_close
```

**Comment by Micro-Crackedto** [comment]
I managed to install the latest version from the repository after trying twice.
This version also gives me an error.

[code]

plugin.video.ziggo - 'description'
                                           Traceback (most recent call last):
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/signals.py", line 29, in throwable
                                               yield
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/router.py", line 94, in dispatch
                                               function(**params)
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/plugin.py", line 43, in decorated_function
                                               item = f(*args, **kwargs)
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/plugin.py", line 68, in login
                                               api.login(username=username, password=password, channels=True)
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 91, in login
                                               self.get_channels_for_user(location=data['locationId'])
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 112, in get_channels_for_user
                                               channeldata = self.get_channel_data(row=row)
                                             File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 130, in get_channel_data
                                               'description': row['stationSchedules'][0]['station']['description'],

**Comment by Micro-Crackedto** [comment]
I just did some additional testing with the HTTP.
I can sign in using email password just fine with your default link "https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/session".

Using the new URL you added, it gives me the following error:
`{"system":"OESP","reason":"wrong backoffice"}`

**Comment by dut-iptv** [comment]
> I also noticed that your z. settings.json [https://dut-epg.github.io/z.settings.json] only contain the new pepper URL as a session instead of prod-obo
Switching this back to prod-obo should be fine as you can see from the data above.

You have got it backwards. the pepper/V2 URL is the old URL, the prod-obo/V3 is the new URL, settings.json is mostly the output of https://ziggogo.tv/nl.settings.json which as of yet does not list the prod-obo/V3 endpoint except in the variable alternativeAjaxBase. My latest addon update changes the pepper/V2 URLs to prod-obo/V3 for those accounts that need to connect to that endpoint.

It seems the login issue is fixed is 0.9.9.21, but the V3 endpoint gives slightly different output for multiple requests, such as the channels listing (which is requested upon successful login). The error you both had with the missing description should be fixed in 0.9.9.22.

The problem with resetting the addon should also be fixed.

A second problem is the fact that all IDs (program ids and channel ids) are different between V2 and V3. So a separate EPG for V3 is required. This is also included in 0.9.9.22

I still don't have an option to test all these changes (as I don't have access to an account that is linked to V3) but I hope you're willing to help me (and yourselves) further along.

What I'm hoping will work in this version:
-Live TV
-Replay TV

What I am expecting not to work as of yet:
-Online Search
-Watchlist
-VOD

Could you guys test the latest version and the above functions and report back what works and what doesn't work.

**Comment by pepijng** [comment]
Ok first test here (clean Kodi install + addon)

1. Live TV from the addon works
2. Enable 'LiveTV' --> Works (including Radio, Guide)
3. Disabled 'Load default channels only' (to test ReplayTV)
    Kodi crashes --> See attached log
4. Disabled 'Load default channels only' --> Works again
[kodi-Disable load default channels.log](https://github.com/dut-iptv/dut-iptv.github.io/files/4897976/kodi-Disable.load.default.channels.log)

**Comment by dut-iptv** [comment]
I don't see any errors in your log.

ReplayTV should work with both "load default channels only" enabled and disabled
Switching that setting will download a larger EPG for customers that have an extended TV package with more channels than the default

At what exact point/action does Kodi crash?
Does it exit fully without any notice or do you receive an error message?

I have uploaded an update (0.9.24) with additional bug fixes

**Comment by pepijng** [comment]
It just crashes when opening a stream.  The reason I turned the setting off is because when I started Replay TV I received the following errormessage.
![image](https://user-images.githubusercontent.com/6169050/87135347-3816ec80-c29a-11ea-8f9c-6fe806adf75e.png)

I just did some testing on .23 and noticed that TV is working using SimpleIPTV but when starting the streams from the addon it also crashes without error. (with load default chanels only enabled)

**Comment by pepijng** [comment]
On Replay TV:
When selecting TV station I get the error message above. When using 'Programs A-Z' I'm able to browse but video does not start en result in an errormessage after several tries.
![image](https://user-images.githubusercontent.com/6169050/87136238-7fea4380-c29b-11ea-872a-e6cc6e67ad99.png)


```
2020-07-10 10:48:26.474 T:5816   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ziggo/?_=play_video&channel=lgi-nl-prod-master%3A0069&id=crid%3A%7E%7E2F%7E%7E2Fbds.tv%7E%7E2F375279630%2Cimi%3Abb47a520889a34a101cbf16b4b80b6e784d6ff82&type=program]
2020-07-10 10:48:37.093 T:5816   ERROR: Previous line repeats 1 times.
2020-07-10 10:48:37.093 T:5816   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ziggo/?_=play_video&channel=lgi-nl-prod-master%3A0069&id=crid%3A%7E%7E2F%7E%7E2Fbds.tv%7E%7E2F375164910%2Cimi%3A99d877c956d08fb2cb80d4907469e7872169fe01&type=program]
2020-07-10 10:48:48.067 T:5816   ERROR: Previous line repeats 1 times.
2020-07-10 10:48:48.067 T:5816   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ziggo/?_=play_video&channel=lgi-nl-prod-master%3A0069&id=crid%3A%7E%7E2F%7E%7E2Fbds.tv%7E%7E2F375279630%2Cimi%3Aed5dec83ba4a6bf43025cd9c041d7b9d02770ac1&type=program]

```

**Comment by dut-iptv** [comment]
The problem with opening ReplayTV listings should be fixed in 0.9.25, this was related to the V3 station ID's which contain a ":" and in turn result in unsafe filenames where the ":" is replaced by an underscore. Because of this kodi could not find the file containing the station EPG.

The problem with not being able to open streams is related to the listing API in V3 not returning the videostreams by default.

@pepijng Could you do the following:
 -Launch chrome/firefox on your computer
-Enable Developer console using Ctrl + Shift + I or F12
-Open the network tab
-Browse to https://www.ziggogo.tv/
-Login to Ziggo Go using your credentials
-Open a show to watch from the guide and start playback
-On the left enter "Orion-DASH" in the search box
-Select that last  of the found entries on the left
-Select the found entry in the network tab
-Right click the the entry and click "Copy" -> "Copy as Powershell"
-Past in a text editor and replace any mention to private information (Tokens and such)
-Copy and paste the resulting output here

**Comment by Nigel1992** [comment]
TV works fine both in the addon and as PVR.
It tells me I don’t have movies and series but I have movies and series XL.
Anything I can do to aid you in resolving this issue ?
Perhaps some HTTP data from the account?

**Comment by pepijng** [comment]
> 
> The problem with not being able to open streams is related to the listing API in V3 not returning the videostreams by default.
> 
> @pepijng Could you do the following:
> -On the left enter "Orion-DASH" in the search box

When filtering on Orion-DASH there are no results. Can you contact me by email (pepijn at pepijn dot com) so I can deliver a full HAR file

**Comment by Nigel1992** [comment]
@pepijng I think its best if we create seperate threads of seperate issues.
