### ISSUE TITLE
[T-Mobile TV] not working

### ISSUE THREAD

**Issue by devrimsen** [dut-iptv/dut-iptv.github.io#23]
plugin.video.tmobile-0.9.97.zip

**T-Mobile TV: Live TV**
![image](https://user-images.githubusercontent.com/56262871/95719005-865bd300-0c6f-11eb-9f04-1cf79924449c.png)
![image](https://user-images.githubusercontent.com/56262871/95719064-97a4df80-0c6f-11eb-8b83-07b5264c322d.png)

_kodi.log_
2020-10-12 09:47:37.683 T:6300   ERROR: plugin.video.tmobile - 'module' object is not callable
                                            Traceback (most recent call last):
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\base\signals.py", line 29, in throwable
                                                yield
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\base\router.py", line 94, in dispatch
                                                function(**params)
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\base\plugin.py", line 35, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\plugin.py", line 104, in live_tv
                                                for row in get_live_channels(addon=settings.getBool(key='enable_simple_iptv')):
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\plugin.py", line 736, in get_live_channels
                                                (_.START_BEGINNING, 'RunPlugin({context_url})'.format(context_url=plugin.url_for(func_or_url=play_video, type='channel', channel=row['id'], id=None, from_beginning=1)), ),
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\base\language.py", line 125, in __getattribute__
                                                return addon_string(attr)
                                              File "C:\Users\Devrim Sen\AppData\Roaming\Kodi\addons\plugin.video.tmobile\resources\lib\base\language.py", line 32, in addon_string
                                                log("LANGUAGE: Addon didn't return a string for id: {}".format(id))
                                            TypeError: 'module' object is not callable

Thereby other options are also not working, as example **Replay TV**

_kodi.log_
2020-10-12 09:51:22.090 T:18132  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.tmobile/?_=play_video&channel=141430714&id=655870793&type=program
2020-10-12 09:51:22.090 T:2456  NOTICE: Creating InputStream
2020-10-12 09:51:52.096 T:2456   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-10-12 09:51:52.096 T:2456   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1/TVOD/42/224/3221236881/3221236881.mpd?playseek=20201011221500-20201011230000&timezone=UTC&rrsip=31.20.164.84:443&zoneoffset=0&devkbps=1-7000&servicetype=3&recType=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&tenantId=3103&accountinfo=j9l2hjeRtkjr1lM1GMagVqhcKeKea8pARwVAu8PpAK%2FHIkeMLWzN3DM%2FcxsEEjUMBXvx6OPkcfVwC72ur77Ho4AwPEKhd%2FuBE5HufB%2BCJsc%3D111f873fa07c15c3c3acc7b4eca4a837%3A20201012075121%3AUTC%2C2163611523_7999734271%2C80.100.222.93%2C20201012075121%2Ce0eb0ce7_edcf_4699_bead_71c98fa03f94%2C2163611523_7999734271%2C-1%2C1%2C300%2C%2C%2C4%2C%2C%2C%2C5%2C-1%2C0%2C10000013492795%2C7999734271%2C%2C%2C5%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAAE2OywqDMBRE_ybL4CtGF1lZCoViC9puyzVeUzEam6jQv6-Kiy5nOGeYyYLEy0nwNE2qBpgXsjSK_KhiXhwGEGHCkphLThx-ciMCIkHrdlC5qTftWWQvnwfU5zTkNPFIue2dNSjh7Wg-9xXaI6xegXZpJYraNXQBR0Epiwqm1gz0ruH7sPpACJbHt2HWmkxbKMF1a0He4DLTj2Cxvhq1c6IB7ZCMIDtQmEOPf97N1uuJH8ThtEHsAAAA:
2020-10-12 09:51:52.096 T:2456   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:0/TVOD/42/224/3221236881/3221236881.mpd?playseek=20201011221500-20201011230000&timezone=UTC&rrsip=31.20.164.84:443&zoneoffset=0&devkbps=1-7000&servicetype=3&recType=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&tenantId=3103&accountinfo=j9l2hjeRtkjr1lM1GMagVqhcKeKea8pARwVAu8PpAK%2FHIkeMLWzN3DM%2FcxsEEjUMBXvx6OPkcfVwC72ur77Ho4AwPEKhd%2FuBE5HufB%2BCJsc%3D111f873fa07c15c3c3acc7b4eca4a837%3A20201012075121%3AUTC%2C2163611523_7999734271%2C80.100.222.93%2C20201012075121%2Ce0eb0ce7_edcf_4699_bead_71c98fa03f94%2C2163611523_7999734271%2C-1%2C1%2C300%2C%2C%2C4%2C%2C%2C%2C5%2C-1%2C0%2C10000013492795%2C7999734271%2C%2C%2C5%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAAE2OywqDMBRE_ybL4CtGF1lZCoViC9puyzVeUzEam6jQv6-Kiy5nOGeYyYLEy0nwNE2qBpgXsjSK_KhiXhwGEGHCkphLThx-ciMCIkHrdlC5qTftWWQvnwfU5zTkNPFIue2dNSjh7Wg-9xXaI6xegXZpJYraNXQBR0Epiwqm1gz0ruH7sPpACJbHt2HWmkxbKMF1a0He4DLTj2Cxvhq1c6IB7ZCMIDtQmEOPf97N1uuJH8ThtEHsAAAA
2020-10-12 09:51:52.096 T:2456   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:0/TVOD/42/224/3221236881/3221236881.mpd?playseek=20201011221500-20201011230000&timezone=UTC&rrsip=31.20.164.84:443&zoneoffset=0&devkbps=1-7000&servicetype=3&recType=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&tenantId=3103&accountinfo=j9l2hjeRtkjr1lM1GMagVqhcKeKea8pARwVAu8PpAK%2FHIkeMLWzN3DM%2FcxsEEjUMBXvx6OPkcfVwC72ur77Ho4AwPEKhd%2FuBE5HufB%2BCJsc%3D111f873fa07c15c3c3acc7b4eca4a837%3A20201012075121%3AUTC%2C2163611523_7999734271%2C80.100.222.93%2C20201012075121%2Ce0eb0ce7_edcf_4699_bead_71c98fa03f94%2C2163611523_7999734271%2C-1%2C1%2C300%2C%2C%2C4%2C%2C%2C%2C5%2C-1%2C0%2C10000013492795%2C7999734271%2C%2C%2C5%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAAE2OywqDMBRE_ybL4CtGF1lZCoViC9puyzVeUzEam6jQv6-Kiy5nOGeYyYLEy0nwNE2qBpgXsjSK_KhiXhwGEGHCkphLThx-ciMCIkHrdlC5qTftWWQvnwfU5zTkNPFIue2dNSjh7Wg-9xXaI6xegXZpJYraNXQBR0Epiwqm1gz0ruH7sPpACJbHt2HWmkxbKMF1a0He4DLTj2Cxvhq1c6IB7ZCMIDtQmEOPf97N1uuJH8ThtEHsAAAA)
2020-10-12 09:51:52.100 T:2456   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.tmobile/?_=play_video&channel=141430714&id=655870793&type=program]
2020-10-12 09:51:52.100 T:2456  NOTICE: CVideoPlayer::OnExit()
2020-10-12 09:51:52.114 T:18132  NOTICE: CVideoPlayer::CloseFile()
2020-10-12 09:51:52.114 T:18132  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-12 09:51:52.114 T:18132  NOTICE: VideoPlayer: finished waiting

**Comment by dut-iptv** [comment]
The error in Live TV is fixed in .99 (will be release shortly)

The error in Replay TV is related to the proxy server that is run by the addon. After first installing or updating the addon it sometimes malfunctions. Restarting Kodi usally fixes this. An extra error message was added in .99 to alert you if the proxy server is not running correctly and advice you to restart

**Comment by devrimsen** [comment]
Thanks for the update, once it is available I will test it and let you know the outcome.

**Comment by devrimsen** [comment]
Performed an initial test and so far everything (live tv, replay tv and etc) is working as expected for plugin.video.tmobile-0.9.97.zip. Thus it seems that the issue has been resolved.
Thanks.
