### ISSUE TITLE
[NLZIET] Unexpected Error

### ISSUE THREAD

**Issue by GuiSCI** [dut-iptv/dut-iptv.github.io#29]
Fout bij het starten van een stream:

`ERROR: plugin.video.nlziet - Expecting value: line 1 column 1 (char 0)
    Traceback (most recent call last):
        File "/home/gui/.kodi/addons/plugin.video.nlziet/resources/lib/base/signals.py", line 29, in throwable
        yield
        File "/home/gui/.kodi/addons/plugin.video.nlziet/resources/lib/base/router.py", line 94, in dispatch
        function(**params)
        File "/home/gui/.kodi/addons/plugin.video.nlziet/resources/lib/base/plugin.py", line 35, in decorated_function
        item = f(*args, **kwargs)
        File "/home/gui/.kodi/addons/plugin.video.nlziet/resources/lib/plugin.py", line 718, in play_video
        playdata = api.play_url(type=type, channel=channel, friendly=friendly, id=id, from_beginning=from_beginning)
        File "/home/gui/.kodi/addons/plugin.video.nlziet/resources/lib/api.py", line 506, in play_url
        download = self.download(url=url_encoded, type='get', headers=None, data=None, json_data=False, return_json=True)
        File "/home/gui/.kodi/addons/plugin.video.nlziet/resources/lib/api.py", line 902, in download
        returned_data = resp.json()
        File "/home/gui/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
        return complexjson.loads(self.text, **kwargs)
        File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
        return _default_decoder.decode(s)
        File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
        File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by dut-iptv** [comment]
When creating an issue please do so in English.

Have you tried again this morning?
I'm expecting NLZiet had some sort of server trouble last night that caused your issue and also caused #28
 
I'll update the addon code to handle the error (caused by not receiving JSON where it is expected), but I expect the root cause is a (temporary) error found at NLZiet

**Comment by GuiSCI** [comment]
Hi, thanks for the fast reply and sorry for the first Dutch message 🙂
You are right, the error happened because of a server issue, that is: me having too many devices connected. I only found out later when my mobile also refused to connect. Thanks for fixing the error message handling, and thanks for the plugin in general! It is much appreciated!
Greetz, Gui

________________________________
Van: dut-iptv <notifications@github.com>
Verzonden: maandag 26 oktober 2020 09:26
Aan: dut-iptv/dut-iptv.github.io <dut-iptv.github.io@noreply.github.com>
CC: Guillaume Thelissen <G.Thelissen@solidcircle.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [dut-iptv/dut-iptv.github.io] [NLZIET] Unexpected Error (#29)


When creating an issue please do so in English.

Have you tried again this morning?
I'm expecting NLZiet had some sort of server trouble last night that caused your issue and also caused #28<https://github.com/dut-iptv/dut-iptv.github.io/issues/28>

I'll update the addon code to handle the error (caused by not receiving JSON where it is expected), but I expect the root cause is a (temporary) error found at NLZiet

**Comment by dut-iptv** [comment]
Good to hear you got it fixed. Enjoy using the addon
