### ISSUE TITLE
Unable to watch Movies & Series XL or ReplayTV

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv.github.io#3]
TV works fine both in the addon and as PVR. on .26
It tells me I don’t have movies and series but I have movies and series XL.
Anything I can do to aid you in resolving this issue?
Perhaps some HTTP data from the account?

**Comment by dut-iptv** [comment]
Please try ReplayTV and Movies & Series XL in 0.9.28. They may/should work.

Online Search and Watchlist have been disabled for V3 for the time being as they will definitely not work right now on V3.

The HAR file supplied by @pepijng was very helpful in figuring out how Movies and Series XL and ReplayTV work in V3.

Are both you guys on a Horizon Box or Next btw?

Could explain why you are on V3, while others are still on V2

**Comment by pepijng** [comment]
I'm on a Next

**Comment by pepijng** [comment]
First test on ReplayTV
![image](https://user-images.githubusercontent.com/6169050/87255795-1d0cce00-c48e-11ea-9106-19c515a47cac.png)
[kodi - ReplayTV.log](https://github.com/dut-iptv/dut-iptv.github.io/files/4909391/kodi.-.ReplayTV.log)

**Comment by pepijng** [comment]
Movies & Series
![image](https://user-images.githubusercontent.com/6169050/87255855-a3291480-c48e-11ea-9bcf-55a78841cb12.png)

```
2020-07-12 22:25:15.296 T:18256   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Ziggo GO('plugin://plugin.video.ziggo/','1','?_=check_entitlements','resume:false')
2020-07-12 22:25:15.296 T:18256   DEBUG: CScriptInvocationManager::GetLanguageInvoker - Reusing LanguageInvokerThread 3 for script C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py
2020-07-12 22:25:15.296 T:15472    INFO: initializing python engine.
2020-07-12 22:25:15.296 T:15472   DEBUG: CPythonInvoker(3, C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): start processing
2020-07-12 22:25:15.296 T:15472   DEBUG: CPythonInvoker(3, C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): entering source directory C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo
2020-07-12 22:25:15.297 T:15472   DEBUG: CPythonInvoker(3, C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\default.py): instantiating addon using automatically obtained id of "plugin.video.ziggo" dependent on version 2.26.0 of the xbmc.python api
2020-07-12 22:25:15.297 T:15472   DEBUG: plugin.video.ziggo - Router Parsed: '?_=check_entitlements' => check_entitlements {'_url': '?_=check_entitlements'}
2020-07-12 22:25:15.297 T:15472   DEBUG: plugin.video.ziggo - SIGNAL: before_dispatch
2020-07-12 22:25:15.298 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.299 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.301 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.302 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.304 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.305 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.307 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.308 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.309 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.310 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.311 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.312 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.313 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.314 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.316 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.317 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.318 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.319 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.320 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.321 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.322 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.323 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.323 T:15472   DEBUG: plugin.video.ziggo - Attempt 1/2: GET https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/mediagroups/feeds/CAT_DATA_VOD__MOVIES_SERIES_XL__Movies__Genres__Actie?byHasCurrentVod=true&range=1-1&sort=playCount7%7Cdesc {'allow_redirects': True, 'timeout': (5, 10)}
2020-07-12 22:25:15.384 T:18252   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-07-12 22:25:15.566 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.567 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.568 T:15472   DEBUG: plugin.video.ziggo - Attempt 1/2: GET https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/mediaitems/crid:~~2F~~2Fog.libertyglobal.com~~2F37500~~2FZINC_52566 {'allow_redirects': True, 'timeout': (5, 10)}
2020-07-12 22:25:15.732 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting definitions
2020-07-12 22:25:15.733 T:15472   DEBUG: CAddonSettings[plugin.video.ziggo]: loading setting values
2020-07-12 22:25:15.734 T:15472   DEBUG: plugin.video.ziggo - SIGNAL: on_exception
2020-07-12 22:25:15.736 T:15472   ERROR: plugin.video.ziggo - list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\signals.py", line 29, in throwable
                                                yield
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\router.py", line 94, in dispatch
                                                function(**params)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\base\plugin.py", line 44, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\plugin.py", line 680, in check_entitlements
                                                urldata = get_play_url(content=data['videoStreams'])
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.ziggo\resources\lib\util.py", line 45, in get_play_url
                                                return {'play_url': content['url'], 'locator': content['contentLocator']}
```
                                            TypeError: list indices must be integers, not str
2020-07-12 22:25:15.736 T:15472   DEBUG: plugin.video.ziggo - SIGNAL: on_close

**Comment by pepijng** [comment]
I've tried a fresh install of Kodi but unfortunately I have the error above on various locations, Also Live TV that does not work anymore.
[kodi.log](https://github.com/dut-iptv/dut-iptv.github.io/files/4909473/kodi.log)

**Comment by dut-iptv** [comment]
0.9.29 uploaded with extra logging and possible fixes for the above three problems

**Comment by Nigel1992** [comment]
Unable to login after resetting the add-on on .30

**Comment by dut-iptv** [comment]
.31 with further fixes.

Sorry for throwing these updates out there is such high succession.

If somethis is not working please provide a debug log containing play testing of:
-Live TV
-Replay TV
-Movies and Series

**Comment by Nigel1992** [comment]
`2020-07-13 14:39:42.641 T:911594368   ERROR: plugin.video.ziggo - global name 'playdata' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/router.py", line 94, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/plugin.py", line 44, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/plugin.py", line 72, in login
                                                check_entitlements()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/plugin.py", line 44, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/plugin.py", line 685, in check_entitlements
                                                return playdata`

**Comment by pepijng** [comment]
Tested on a clean install

After (initial) logon this error occured
![image](https://user-images.githubusercontent.com/6169050/87306114-d663b600-c517-11ea-96f8-803fa8c44280.png)


**Live TV --> Works**
**Replay TV --> Works** 
if selecting a title from The A-Z menu, selection from a TV channel (for example NPO1) this error occurs
![image](https://user-images.githubusercontent.com/6169050/87306297-1d51ab80-c518-11ea-8e3a-c57141134e67.png)

**Movies & Series --> Works**

Attached a full log-file of this testing session
[kodi.log](https://github.com/dut-iptv/dut-iptv.github.io/files/4912544/kodi.log)

**Comment by dut-iptv** [comment]
.32 uploaded which should fix the error on login (BTW login still succeeds, but checking if you have access to Movies and Series failed)

Should also fix the No ReplayTV information available error

What I can see from the logs @pepijng sent is that the addon in V3 mode still fails in loading seasons in Movies and Series. Season loading is different from V2 and I still don't have enough information to figure out how this works in V3

Would one of you be able to do the following:
-Launch chrome/firefox on your computer
-Enable Developer console using Ctrl + Shift + I or F12
-Open the network tab
-Browse to https://www.ziggogo.tv/
-Clear the contents of the network tab using the clear button
-Login to Ziggo Go using your credentials
-Open Movies & Series
-Go to Series
-Open "Billions"
-Click on "Season 2"
-On the left enter "Optimal Play" in the search box
-Select the found entry in the network tab
-Right click the the entry and click "Copy" -> "Copy as Powershell"
-Past in a text editor and replace any mention to private information (Tokens and such)
-Copy and paste the resulting output here

**Comment by Nigel1992** [comment]
Everything works apart from the Series.
Movies and HBO Movies all work fine.
Here's the log you requested.

`Invoke-WebRequest -Uri "https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/mediaitems?byMediaType=Episode%7CFeatureFilm&byParentId=crid%3A~~2F~~2Fog.libertyglobal.com~~2F37500~~2FZ136861&includeAdult=true&range=1-165&sort=seriesEpisodeNumber%7CASC" `
-Headers @{
"Accept"="application/json"
  "X-OESP-Token"="PRIVATE"
  "X-Client-Id"="1.4.25.14||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
  "X-OESP-Username"="PRIVATE"
  "X-OESP-Profile-Id"="PRIVATE"
  "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
  "Origin"="https://www.ziggogo.tv"
  "Sec-Fetch-Site"="cross-site"
  "Sec-Fetch-Mode"="cors"
  "Sec-Fetch-Dest"="empty"
  "Referer"="https://www.ziggogo.tv/obo_nl/movies-series-xl/vod-asset.html/crid%3A~~2F~~2Fog.libertyglobal.com~~2F37500~~2FBILLIONS/afl-01-risk-management/crid%3A~~2F~~2Fog.libertyglobal.com~~2F37500~~2FZINC_52998/risk-management.html"
  "Accept-Encoding"="gzip, deflate, br"
  "Accept-Language"="en-US,en;q=0.9"
} `
-ContentType "application/json"`

**Comment by Nigel1992** [comment]
Thanks for all your hard work.
Seasons are still showing "No Items" though.

**Comment by dut-iptv** [comment]
Now definitely fixed in .34

**Comment by Nigel1992** [comment]
Everything works now.
Thanks for all your work.

**Comment by dut-iptv** [comment]
@Nigel1992 @pepijng 
Thanks for your input.
Hope you are willing to help test Wachtlists and search.
Will make a new issue to test when I have an update ready.

Closing
