### ISSUE TITLE
[CanalDigitaal] Error when launching the addon

### ISSUE THREAD

**Issue by xanthox** [dut-iptv/dut-iptv.github.io#31]
I tried to use this addon on Libreelec 9.2.4 (Kodi Leia) on a raspberry3, but if I click the addon I get this error:

`2020-10-27 09:35:23.875 T:1190679424   ERROR: plugin.video.kpn - global name 'ADDON_NAME' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/base/router.py", line 98, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/base/plugin.py", line 24, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/plugin.py", line 34, in home
                                                first_boot()
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/plugin.py", line 739, in first_boot
                                                if gui.yes_no(message=_.SET_IPTV):
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/base/gui.py", line 74, in yes_no
                                                heading = _make_heading(heading)
                                              File "/storage/.kodi/addons/plugin.video.kpn/resources/lib/base/gui.py", line 5, in _make_heading
                                                return heading if heading else ADDON_NAME
                                            NameError: global name 'ADDON_NAME' is not defined`

I have tried Ziggo and Canaal Digital as well, they throw the same error though. (For CD):

`2020-10-27 09:22:21.498 T:1125217152   ERROR: plugin.video.canaldigitaal - global name 'ADDON_NAME' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 98, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 24, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 34, in home
                                                first_boot()
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 708, in first_boot
                                                if gui.yes_no(message=_.SET_IPTV):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/gui.py", line 74, in yes_no
                                                heading = _make_heading(heading)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/gui.py", line 5, in _make_heading
                                                return heading if heading else ADDON_NAME
                                            NameError: global name 'ADDON_NAME' is not defined
2020-10-27 09:22:30.333 T:1007719296   ERROR: GetDirectory - Error getting plugin://plugin.video.canaldigitaal/
2020-10-27 09:22:30.342 T:1936888880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canaldigitaal/) failed
2020-10-27 09:22:37.114 T:1125217152   ERROR: plugin.video.canaldigitaal - global name 'ADDON_NAME' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 98, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 24, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 34, in home
                                                first_boot()
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 708, in first_boot
                                                if gui.yes_no(message=_.SET_IPTV):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/gui.py", line 74, in yes_no
                                                heading = _make_heading(heading)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/gui.py", line 5, in _make_heading
                                                return heading if heading else ADDON_NAME
                                            NameError: global name 'ADDON_NAME' is not defined`

I have a CD account as I am a subscriber, thought I'd install KPN as well to see if I would get the same error, and that seems to be the case. Any idea?

**Comment by xanthox** [comment]
Meh. Need to fix the python issue that is in the install document I see now...

**Comment by dut-iptv** [comment]
You don't need to follow the extra installation instructions on Libreelec.

I broke something today in the common base of all the addons.
Thanks for the report.

Should be fixed in .107

**Comment by dut-iptv** [comment]
I don't have access to a CD account right now btw, so I am wondering if playback (Live/Replay) on CD works at all right now.

**Comment by xanthox** [comment]
> 
> 
> I don't have access to a CD account right now btw, so I am wondering if playback (Live/Replay) on CD works at all right now.

I can test that for you as soon as .107 is out

**Comment by dut-iptv** [comment]
It is already on github. Force kodi to look for updates and it should find it

**Comment by xanthox** [comment]
I can fill in the login details and afterwards I get this error:

`2020-10-27 10:42:17.988 T:609203072   ERROR: plugin.video.canaldigitaal - no such column: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0di5zb2xvY29vLmF1dGgiOnsicyI6Inc2YTYyYjZlNi0zMGE0LTRmYWEtYTQ1MC1jYjg2NjA3MjU1ZmMiLCJ1IjoiakFSTVc2T2dIdHd1TzM3YnlqSjh2USIsImQiOiJQQyIsIm9tIjoiTyIsImMiOiJpVktlUFc0dWdfQWdFSU5kYjJVbWEtUmVqOU1QZnEtVFVJejhmSmg1ckFZIiwic3QiOiJmdWxsIiwiZyI6ImV5SmtZaUk2Wm1Gc2MyVXNJbkIwSWpwbVlXeHpaU3dpWW5JaU9pSmpaSE1pTENKa1pTSTZJbk5oY0dsVWIydGxiaUlzSW5Wd0lqb2liVGRpWlRJaWZRIn0sIm5iZiI6MTYwMzc5NTMzNiwiZXhwIjoxNjAzNzk3MTM2LCJpYXQiOjE2MDM3OTUzMzYsImF1ZCI6Im03YmUyIn0.KPX
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 98, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 24, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 84, in login
                                                login_result = api.login()
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/api.py", line 187, in login
                                                query_settings(query=query, return_result=False, return_insert=False, commit=True)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/util.py", line 602, in query_settings
                                                return query_db(db_file=SETTINGS_DB_FILE, query=query, return_result=return_result, return_insert=return_insert, commit=commit)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/util.py", line 633, in query_db
                                                cur.execute(query)
                                            OperationalError: no such column: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0di5zb2xvY29vLmF1dGgiOnsicyI6Inc2YTYyYjZlNi0zMGE0LTRmYWEtYTQ1MC1jYjg2NjA3MjU1ZmMiLCJ1IjoiakFSTVc2T2dIdHd1TzM3YnlqSjh2USIsImQiOiJQQyIsIm9tIjoiTyIsImMiOiJpVktlUFc0dWdfQWdFSU5kYjJVbWEtUmVqOU1QZnEtVFVJejhmSmg1ckFZIiwic3QiOiJmdWxsIiwiZyI6ImV5SmtZaUk2Wm1Gc2MyVXNJbkIwSWpwbVlXeHpaU3dpWW5JaU9pSmpaSE1pTENKa1pTSTZJbk5oY0dsVWIydGxiaUlzSW5Wd0lqb2liVGRpWlRJaWZRIn0sIm5iZiI6MTYwMzc5NTMzNiwiZXhwIjoxNjAzNzk3MTM2LCJpYXQiOjE2MDM3OTUzMzYsImF1ZCI6Im03YmUyIn0.KPX`

I have room to add an extra device (checked)

**Comment by dut-iptv** [comment]
Improperly escaped SQLite. Should be fixed.

Please try again with .108

**Comment by Kevigsp** [comment]
Just tryed CanalDigital.
it worked, but won't login.
keeps returning:
"fout bij inloggen, controleer je emailadres en wachtwoord"
beide zijn juist en werken

**Comment by xanthox** [comment]
>  "fout bij inloggen, controleer je emailadres en wachtwoord"

Yeah, check in the app (or website) if you have room to login. If you exceed their 4 devices, you will get a password error with this plugin. If you use the website, a popup will inform you have to clear a device in order to login. I used the app to check how many devices are registered. (start app, right click your icon/avatar below in the corner. Under 'Apparaten' check 'Overzicht gekoppelde apparaten'. It sees my Kodi plugin as Chrome.

**Comment by xanthox** [comment]
> 
> 
> Improperly escaped SQLite. Should be fixed.
> 
> Please try again with .108

Tested it. Can retrieve the channel list. When trying RTL 5:

`2020-10-27 12:53:31.201 T:1553023872   ERROR: plugin.video.canaldigitaal - local variable 'info' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 98, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 24, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 577, in play_video
                                                playdata = api.play_url(type=type, channel=channel, id=id, from_beginning=from_beginning)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/api.py", line 560, in play_url
                                                playdata = {'path': path, 'license': license, 'info': info}
                                            UnboundLocalError: local variable 'info' referenced before assignment`

I also checked Replay TV, but as soon as you click on that one, you'll get:

`2020-10-27 12:54:00.942 T:1553023872   ERROR: plugin.video.canaldigitaal - 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 98, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 24, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 131, in replaytv
                                                for row in get_replay_channels():
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 816, in get_replay_channels
                                                'path': plugin.url_for(func_or_url=replaytv_by_day, image=row['icon'], description=row['description'], label=row['name'], station=row['id']),
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 60, in url_for
                                                return url_for_func(func_or_url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 54, in url_for_func
                                                return build_url(url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 88, in build_url
                                                return 'plugin://{0}/?{1}'.format(addon_id, urlencode(encode_obj(params)))
                                              File "/usr/lib/python2.7/urllib.py", line 1342, in urlencode
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
2020-10-27 12:54:04.364 T:1174180736   ERROR: GetDirectory - Error getting plugin://plugin.video.canaldigitaal/?_=replaytv
2020-10-27 12:54:04.369 T:1937021376   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.canaldigitaal/?_=replaytv) failed
`

**Comment by Kevigsp** [comment]
just tried it.
i had 5 devices, cleared 4 of them, but still got the error "fout bij inloggen"

**Comment by xanthox** [comment]
> 
> 
> just tried it.
> i had 5 devices, cleared 4 of them, but still got the error "fout bij inloggen"

Strange, here it worked when I cleared my devices. Did not even reset the addon. Check if you can login at [their website](https://livetv.canaldigitaal.nl) to see if it works. Double check password, and if not, check the logs.

**Comment by Kevigsp** [comment]
Login just work, perhaps it needed some time, did not change a thing!

**Comment by dut-iptv** [comment]
Problems are under investigation

**Comment by dut-iptv** [comment]
Please check if .109 gets you further along on Live and ReplayTV

**Comment by xanthox** [comment]
Thanks for your continues development in this addon! Much appreciated.

Live TV works, I just checked RTL5 and NPO1 which are working. Widevine was downloaded.

Replay TV did not work. I tried NPO3 and RTL4 (yesterday):

`2020-10-29 15:58:23.653 T:1028830080   ERROR: plugin.video.canaldigitaal - global name 'time' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/router.py", line 93, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/base/plugin.py", line 25, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/plugin.py", line 654, in play_video
                                                info = plugin_process_info(playdata)
                                              File "/storage/.kodi/addons/plugin.video.canaldigitaal/resources/lib/util.py", line 64, in plugin_process_info
                                                startT = datetime.datetime.fromtimestamp(time.mktime(time.strptime(playdata['info']['params']['start'], "%Y-%m-%dT%H:%M:%SZ")))
                                            NameError: global name 'time' is not defined`

**Comment by dut-iptv** [comment]
Thanks for testing and the latest report. A very small bug remains based on your log. Will be fixed tomorrow.

**Comment by dut-iptv** [comment]
Version .110 is in the Repo now with a fix for the error in ReplayTV

**Comment by xanthox** [comment]
> 
> 
> Version .110 is in the Repo now with a fix for the error in ReplayTV

All is working, checked both Live TV and replay TV. Nice work!

**Comment by dut-iptv** [comment]
Good to hear, closing
