### ISSUE TITLE
[Ziggo] Error message even without use of addon

### ISSUE THREAD

**Issue by kingkong2332** [dut-iptv/dut-iptv.github.io#41]
Very grateful for this amazing addon!

During the use of Kodi I receive the error message below at random moments:

_2020-11-10 09:57:58.027 T:140100843247360   ERROR: plugin.video.ziggo - database disk image is malformed
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/router.py", line 93, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/plugin.py", line 25, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/plugin.py", line 92, in live_tv
                                                for row in get_live_channels(addon=settings.getBool(key='enable_simple_iptv')):
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/plugin.py", line 795, in get_live_channels
                                                data = query_epg(query=query, return_result=True, return_insert=False, commit=False)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/util.py", line 599, in query_epg
                                                return query_db(db_file=EPG_DB_FILE, query=query, return_result=return_result, return_insert=return_insert, commit=commit)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/util.py", line 631, in query_db
                                                cur.execute(query)
                                            DatabaseError: database disk image is malformed_

My setup is on Libreelec 9.2.6.

**Comment by dut-iptv** [comment]
Based on your log the settings.db of your install got corrupted. This is usually the result of sudden power loss or killing kodi while it is writing to the db.

Reset the addon from the settings and reconfigure.

**Comment by kingkong2332** [comment]
It seems the error message has been resolved after a reset. Thanks for the feedback!
