### ISSUE TITLE
[Ziggo][V3] Movies and Series not working

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv.github.io#6]
Hi,

I am unable to watch any movie and series so I decided to reset the addon and logout.
It now throws me an error regarding the encryption when trying to sign in.

`2020-08-19 03:14:31.277 T:967771008   ERROR: plugin.video.ziggo - Incorrect IV length (it must be 16 bytes long)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/router.py", line 92, in dispatch
                                                signals.emit(signals.BEFORE_DISPATCH)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/signals.py", line 24, in emit
                                                f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/plugin.py", line 757, in before_dispatch
                                                api.new_session()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 24, in new_session
                                                creds = get_credentials()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/util.py", line 250, in get_credentials
                                                return Credentials().decode_credentials(username, password)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/encrypt.py", line 27, in decode_credentials
                                                'password': self.decode(enc=password)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/encrypt.py", line 44, in decode
                                                cipher = AES.new(self.crypt_key, AES.MODE_CBC, iv)
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 232, in new
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 288, in _create_cbc_cipher
                                            ValueError: Incorrect IV length (it must be 16 bytes long) `

**Comment by dut-iptv** [comment]
Seems like a bug in the password encryption/decryption. Will investigate. 

In the meantime please reset the addon, dont logout after but restart kodi and re-enter your credentials afterwards. If you still dont have access to movies and series afterwards please report back. Also check live/replay to make sure those work.

**Comment by dut-iptv** [comment]
Base problem possibly related to general Ziggo Go outage. See https://tweakers.net/nieuws/171142/ziggo-go-kampt-met-storing.html

**Comment by Nigel1992** [comment]
> Base problem possibly related to general Ziggo Go outage. See https://tweakers.net/nieuws/171142/ziggo-go-kampt-met-storing.html

I managed to log in without any issues now, but its saying I don't have Movies & Series.
I guess we have to wait for Ziggo to fix it :P

**Comment by dut-iptv** [comment]
You can manually change if the addon shows Movies and Series by changing the option in the Addon settings

**Comment by Nigel1992** [comment]
Stil says I dont have access.
I can watch perfectly fine using ziggogo.nl

**Comment by dut-iptv** [comment]
Hopefully fixed in 9.9.38.
Please update and check entitlements from the settings menu

**Comment by Nigel1992** [comment]
Seems to be fully fixed, thanks!

**Comment by dut-iptv** [comment]
Good to hear. Tnx for your debugging. Lets hope Ziggo will keep things stable and without any changes for a while
